# Generated by Django 2.0.9 on 2019-01-31 20:54

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('image', models.ImageField(upload_to='Images', verbose_name='صورة مناسبة')),
                ('prix', models.CharField(max_length=200, verbose_name='ملتقط الصورة')),
                ('prix_colobal', models.CharField(max_length=200, verbose_name='المصدر')),
                ('body', models.TextField(max_length=500)),
                ('number', models.IntegerField()),
                ('wilaya', models.CharField(max_length=200, verbose_name='ملتقط الصورة')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='Avatar/deafult-profile-image.png', upload_to='Avatar')),
                ('firstname', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relation', models.CharField(blank=True, max_length=500, null=True)),
                ('pays', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_category', models.ImageField(blank=True, null=True, upload_to='Category_images')),
                ('color', colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF', '#17a589'])),
            ],
        ),
        migrations.CreateModel(
            name='comment_put',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('avatar_commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogArabic.author')),
                ('user_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_put', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogArabic.articles')),
            ],
        ),
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('text_body', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogArabic.author'),
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='blogArabic.Category'),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
