# Generated by Django 2.0.9 on 2019-01-31 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyltiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('multi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogArabic.articles')),
            ],
        ),
    ]
