# Generated by Django 2.0.9 on 2019-01-31 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0002_myltiimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myltiimage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='myltiimage',
            name='multi',
        ),
        migrations.AddField(
            model_name='myltiimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myltiimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogArabic.articles'),
        ),
    ]
