# Generated by Django 2.0.9 on 2019-02-01 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogArabic', '0004_auto_20190201_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='baladiya',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='البلدية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='prix',
            field=models.CharField(max_length=200, verbose_name='سعر الكلوغرام الواحد'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='prix_colobal',
            field=models.CharField(max_length=200, verbose_name='السعر بالجملة'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='wilaya',
            field=models.CharField(max_length=200, verbose_name='الولاية'),
        ),
    ]
